#!/usr/bin/env bash
set -e
export BAGCLI_WORKDIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
. "$BAGCLI_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
Avallone CLI
Version: $(cat $BAGCLI_WORKDIR/VERSION)
https://github.com/ahmadnazir/avallone-cli

Usage: $cli_name [command]

Commands:
  k9s       K9s for tests stacks
  *         Help
"
  exit 1
}

cli_log "Reading configuration"
[ ! -f "$CONFIG_DIR/config" ] \
  && echo "ERROR: No $CONFIG_DIR/config file found. " \
  && echo "Run install script." \
  && exit 1

export $(cat "$CONFIG_DIR/config" | xargs)

case "$1" in
  k9s|k)
    "$BAGCLI_WORKDIR/commands/k9s" "$2" | tee -ia "$BAGCLI_WORKDIR/logs/k9s_${2}.log"
    ;;
  *)
    cli_help
    ;;
esac
