#!/usr/bin/env bash
CONFIG_DIR=~/.config/avallone-cli
cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

CALIBURNUS_PATH=~/code/avallone/caliburnus
BACKEND_SERVICES_PATH=~/code/avallone/backend-services
