#!/usr/bin/env bash
set -e
export WORKDIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
. "$WORKDIR/common"

BIN_FILE=~/.local/bin/avallone
cli_log "Installing: $BIN_FILE"
ln -s $WORKDIR/avallone-cli $BIN_FILE

CONFIG_FILE=$CONFIG_DIR/config
cli_log "Setting up default configuration: $CONFIG_FILE"
mkdir -p $CONFIG_DIR
cp $WORKDIR/config.template $CONFIG_FILE

cli_log "Done!"
