#!/usr/bin/env bash
set -e
. "$WORKDIR/common"

cli_log "Configuring credentials"
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

aws sts assume-role --role-arn $AVALLONE_KLUSTER_ROLE_ARN --role-session-name my-kubernetes-session > /tmp/aws-role-credentials.json

export AWS_ACCESS_KEY_ID=`jq '.Credentials.AccessKeyId' -rj /tmp/aws-role-credentials.json`
export AWS_SECRET_ACCESS_KEY=`jq '.Credentials.SecretAccessKey' -rj /tmp/aws-role-credentials.json`
export AWS_SESSION_TOKEN=`jq '.Credentials.SessionToken' -rj /tmp/aws-role-credentials.json`

cli_log "Starting k9s"

k9s
